-- Insert 100 test records into log_entries table
-- This SQL script creates 100 sample log entries with various event names and validation statuses
-- to test pagination functionality

INSERT INTO log_entries (
    app_id,
    event_name,
    payload,
    validation_status,
    validation_results,
    created_at
) VALUES
(1, 'UserLogin', '{"username": "user1", "timestamp": "2025-11-04T10:00:00"}', 'Valid', '[{"key": "username", "value": "user1", "validationStatus": "Valid"}]', NOW() - INTERVAL 99 MINUTE),
(1, 'UserLogout', '{"username": "user1", "timestamp": "2025-11-04T10:01:00"}', 'Valid', '[{"key": "username", "value": "user1", "validationStatus": "Valid"}]', NOW() - INTERVAL 98 MINUTE),
(1, 'UserLogin', '{"username": "user2", "timestamp": "2025-11-04T10:02:00"}', 'Valid', '[{"key": "username", "value": "user2", "validationStatus": "Valid"}]', NOW() - INTERVAL 97 MINUTE),
(1, 'ProfileUpdate', '{"userId": 1, "field": "email"}', 'Valid', '[{"key": "userId", "value": 1, "validationStatus": "Valid"}]', NOW() - INTERVAL 96 MINUTE),
(1, 'UserLogin', '{"username": "user3", "timestamp": "2025-11-04T10:04:00"}', 'Invalid', '[{"key": "username", "value": "user3", "validationStatus": "Valid"}, {"key": "timestamp", "value": "invalid", "validationStatus": "Invalid"}]', NOW() - INTERVAL 95 MINUTE),
(1, 'DataSync', '{"syncId": "sync001", "records": 50}', 'Valid', '[{"key": "syncId", "value": "sync001", "validationStatus": "Valid"}]', NOW() - INTERVAL 94 MINUTE),
(1, 'UserLogin', '{"username": "user4", "timestamp": "2025-11-04T10:06:00"}', 'Valid', '[{"key": "username", "value": "user4", "validationStatus": "Valid"}]', NOW() - INTERVAL 93 MINUTE),
(1, 'ErrorEvent', '{"errorCode": 500, "message": "Server error"}', 'Invalid', '[{"key": "errorCode", "value": 500, "validationStatus": "Valid"}, {"key": "message", "value": "Server error", "validationStatus": "Invalid"}]', NOW() - INTERVAL 92 MINUTE),
(1, 'UserLogout', '{"username": "user2", "timestamp": "2025-11-04T10:08:00"}', 'Valid', '[{"key": "username", "value": "user2", "validationStatus": "Valid"}]', NOW() - INTERVAL 91 MINUTE),
(1, 'PageView', '{"pageId": "home", "duration": 5000}', 'Valid', '[{"key": "pageId", "value": "home", "validationStatus": "Valid"}]', NOW() - INTERVAL 90 MINUTE),
(1, 'UserLogin', '{"username": "user5", "timestamp": "2025-11-04T10:10:00"}', 'Valid', '[{"key": "username", "value": "user5", "validationStatus": "Valid"}]', NOW() - INTERVAL 89 MINUTE),
(1, 'ClickEvent', '{"elementId": "btn123", "clickCount": 3}', 'Valid', '[{"key": "elementId", "value": "btn123", "validationStatus": "Valid"}]', NOW() - INTERVAL 88 MINUTE),
(1, 'UserLogin', '{"username": "user6", "timestamp": "2025-11-04T10:12:00"}', 'Valid', '[{"key": "username", "value": "user6", "validationStatus": "Valid"}]', NOW() - INTERVAL 87 MINUTE),
(1, 'FormSubmit', '{"formId": "contact", "fields": 5}', 'Valid', '[{"key": "formId", "value": "contact", "validationStatus": "Valid"}]', NOW() - INTERVAL 86 MINUTE),
(1, 'UserLogin', '{"username": "user7", "timestamp": "2025-11-04T10:14:00"}', 'Invalid', '[{"key": "username", "value": "", "validationStatus": "Invalid"}]', NOW() - INTERVAL 85 MINUTE),
(1, 'DataSync', '{"syncId": "sync002", "records": 100}', 'Valid', '[{"key": "syncId", "value": "sync002", "validationStatus": "Valid"}]', NOW() - INTERVAL 84 MINUTE),
(1, 'UserLogout', '{"username": "user3", "timestamp": "2025-11-04T10:16:00"}', 'Valid', '[{"key": "username", "value": "user3", "validationStatus": "Valid"}]', NOW() - INTERVAL 83 MINUTE),
(1, 'PageView', '{"pageId": "products", "duration": 15000}', 'Valid', '[{"key": "pageId", "value": "products", "validationStatus": "Valid"}]', NOW() - INTERVAL 82 MINUTE),
(1, 'UserLogin', '{"username": "user8", "timestamp": "2025-11-04T10:18:00"}', 'Valid', '[{"key": "username", "value": "user8", "validationStatus": "Valid"}]', NOW() - INTERVAL 81 MINUTE),
(1, 'ClickEvent', '{"elementId": "btn456", "clickCount": 1}', 'Valid', '[{"key": "elementId", "value": "btn456", "validationStatus": "Valid"}]', NOW() - INTERVAL 80 MINUTE),
(1, 'UserLogin', '{"username": "user9", "timestamp": "2025-11-04T10:20:00"}', 'Valid', '[{"key": "username", "value": "user9", "validationStatus": "Valid"}]', NOW() - INTERVAL 79 MINUTE),
(1, 'ErrorEvent', '{"errorCode": 404, "message": "Not found"}', 'Valid', '[{"key": "errorCode", "value": 404, "validationStatus": "Valid"}]', NOW() - INTERVAL 78 MINUTE),
(1, 'UserLogout', '{"username": "user4", "timestamp": "2025-11-04T10:22:00"}', 'Valid', '[{"key": "username", "value": "user4", "validationStatus": "Valid"}]', NOW() - INTERVAL 77 MINUTE),
(1, 'ProfileUpdate', '{"userId": 2, "field": "phone"}', 'Valid', '[{"key": "userId", "value": 2, "validationStatus": "Valid"}]', NOW() - INTERVAL 76 MINUTE),
(1, 'UserLogin', '{"username": "user10", "timestamp": "2025-11-04T10:24:00"}', 'Valid', '[{"key": "username", "value": "user10", "validationStatus": "Valid"}]', NOW() - INTERVAL 75 MINUTE),
(1, 'DataSync', '{"syncId": "sync003", "records": 75}', 'Valid', '[{"key": "syncId", "value": "sync003", "validationStatus": "Valid"}]', NOW() - INTERVAL 74 MINUTE),
(1, 'PageView', '{"pageId": "checkout", "duration": 30000}', 'Valid', '[{"key": "pageId", "value": "checkout", "validationStatus": "Valid"}]', NOW() - INTERVAL 73 MINUTE),
(1, 'UserLogin', '{"username": "user11", "timestamp": "2025-11-04T10:26:00"}', 'Valid', '[{"key": "username", "value": "user11", "validationStatus": "Valid"}]', NOW() - INTERVAL 72 MINUTE),
(1, 'FormSubmit', '{"formId": "login", "fields": 2}', 'Valid', '[{"key": "formId", "value": "login", "validationStatus": "Valid"}]', NOW() - INTERVAL 71 MINUTE),
(1, 'UserLogout', '{"username": "user5", "timestamp": "2025-11-04T10:28:00"}', 'Valid', '[{"key": "username", "value": "user5", "validationStatus": "Valid"}]', NOW() - INTERVAL 70 MINUTE),
(1, 'ClickEvent', '{"elementId": "link789", "clickCount": 2}', 'Valid', '[{"key": "elementId", "value": "link789", "validationStatus": "Valid"}]', NOW() - INTERVAL 69 MINUTE),
(1, 'UserLogin', '{"username": "user12", "timestamp": "2025-11-04T10:30:00"}', 'Invalid', '[{"key": "username", "value": "user12", "validationStatus": "Valid"}, {"key": "timestamp", "value": null, "validationStatus": "Invalid"}]', NOW() - INTERVAL 68 MINUTE),
(1, 'ErrorEvent', '{"errorCode": 403, "message": "Forbidden"}', 'Invalid', '[{"key": "errorCode", "value": 403, "validationStatus": "Valid"}, {"key": "message", "value": null, "validationStatus": "Invalid"}]', NOW() - INTERVAL 67 MINUTE),
(1, 'UserLogin', '{"username": "user13", "timestamp": "2025-11-04T10:32:00"}', 'Valid', '[{"key": "username", "value": "user13", "validationStatus": "Valid"}]', NOW() - INTERVAL 66 MINUTE),
(1, 'PageView', '{"pageId": "dashboard", "duration": 60000}', 'Valid', '[{"key": "pageId", "value": "dashboard", "validationStatus": "Valid"}]', NOW() - INTERVAL 65 MINUTE),
(1, 'DataSync', '{"syncId": "sync004", "records": 200}', 'Valid', '[{"key": "syncId", "value": "sync004", "validationStatus": "Valid"}]', NOW() - INTERVAL 64 MINUTE),
(1, 'UserLogout', '{"username": "user6", "timestamp": "2025-11-04T10:34:00"}', 'Valid', '[{"key": "username", "value": "user6", "validationStatus": "Valid"}]', NOW() - INTERVAL 63 MINUTE),
(1, 'UserLogin', '{"username": "user14", "timestamp": "2025-11-04T10:36:00"}', 'Valid', '[{"key": "username", "value": "user14", "validationStatus": "Valid"}]', NOW() - INTERVAL 62 MINUTE),
(1, 'ClickEvent', '{"elementId": "menu001", "clickCount": 5}', 'Valid', '[{"key": "elementId", "value": "menu001", "validationStatus": "Valid"}]', NOW() - INTERVAL 61 MINUTE),
(1, 'FormSubmit', '{"formId": "register", "fields": 8}', 'Valid', '[{"key": "formId", "value": "register", "validationStatus": "Valid"}]', NOW() - INTERVAL 60 MINUTE),
(1, 'ProfileUpdate', '{"userId": 3, "field": "address"}', 'Valid', '[{"key": "userId", "value": 3, "validationStatus": "Valid"}]', NOW() - INTERVAL 59 MINUTE),
(1, 'UserLogin', '{"username": "user15", "timestamp": "2025-11-04T10:38:00"}', 'Valid', '[{"key": "username", "value": "user15", "validationStatus": "Valid"}]', NOW() - INTERVAL 58 MINUTE),
(1, 'UserLogout', '{"username": "user7", "timestamp": "2025-11-04T10:40:00"}', 'Valid', '[{"key": "username", "value": "user7", "validationStatus": "Valid"}]', NOW() - INTERVAL 57 MINUTE),
(1, 'PageView', '{"pageId": "settings", "duration": 8000}', 'Valid', '[{"key": "pageId", "value": "settings", "validationStatus": "Valid"}]', NOW() - INTERVAL 56 MINUTE),
(1, 'UserLogin', '{"username": "user16", "timestamp": "2025-11-04T10:42:00"}', 'Valid', '[{"key": "username", "value": "user16", "validationStatus": "Valid"}]', NOW() - INTERVAL 55 MINUTE),
(1, 'DataSync', '{"syncId": "sync005", "records": 150}', 'Valid', '[{"key": "syncId", "value": "sync005", "validationStatus": "Valid"}]', NOW() - INTERVAL 54 MINUTE),
(1, 'ErrorEvent', '{"errorCode": 500, "message": "Internal error"}', 'Invalid', '[{"key": "errorCode", "value": 500, "validationStatus": "Valid"}, {"key": "message", "value": "Internal error", "validationStatus": "Invalid"}]', NOW() - INTERVAL 53 MINUTE),
(1, 'UserLogin', '{"username": "user17", "timestamp": "2025-11-04T10:44:00"}', 'Valid', '[{"key": "username", "value": "user17", "validationStatus": "Valid"}]', NOW() - INTERVAL 52 MINUTE),
(1, 'ClickEvent', '{"elementId": "banner001", "clickCount": 1}', 'Valid', '[{"key": "elementId", "value": "banner001", "validationStatus": "Valid"}]', NOW() - INTERVAL 51 MINUTE),
(1, 'UserLogout', '{"username": "user8", "timestamp": "2025-11-04T10:46:00"}', 'Valid', '[{"key": "username", "value": "user8", "validationStatus": "Valid"}]', NOW() - INTERVAL 50 MINUTE),
(1, 'FormSubmit', '{"formId": "feedback", "fields": 4}', 'Valid', '[{"key": "formId", "value": "feedback", "validationStatus": "Valid"}]', NOW() - INTERVAL 49 MINUTE),
(1, 'UserLogin', '{"username": "user18", "timestamp": "2025-11-04T10:48:00"}', 'Valid', '[{"key": "username", "value": "user18", "validationStatus": "Valid"}]', NOW() - INTERVAL 48 MINUTE),
(1, 'PageView', '{"pageId": "help", "duration": 3000}', 'Valid', '[{"key": "pageId", "value": "help", "validationStatus": "Valid"}]', NOW() - INTERVAL 47 MINUTE),
(1, 'UserLogout', '{"username": "user9", "timestamp": "2025-11-04T10:50:00"}', 'Valid', '[{"key": "username", "value": "user9", "validationStatus": "Valid"}]', NOW() - INTERVAL 46 MINUTE),
(1, 'UserLogin', '{"username": "user19", "timestamp": "2025-11-04T10:52:00"}', 'Valid', '[{"key": "username", "value": "user19", "validationStatus": "Valid"}]', NOW() - INTERVAL 45 MINUTE),
(1, 'DataSync', '{"syncId": "sync006", "records": 125}', 'Valid', '[{"key": "syncId", "value": "sync006", "validationStatus": "Valid"}]', NOW() - INTERVAL 44 MINUTE),
(1, 'ProfileUpdate', '{"userId": 4, "field": "timezone"}', 'Valid', '[{"key": "userId", "value": 4, "validationStatus": "Valid"}]', NOW() - INTERVAL 43 MINUTE),
(1, 'UserLogin', '{"username": "user20", "timestamp": "2025-11-04T10:54:00"}', 'Valid', '[{"key": "username", "value": "user20", "validationStatus": "Valid"}]', NOW() - INTERVAL 42 MINUTE),
(1, 'ClickEvent', '{"elementId": "social001", "clickCount": 2}', 'Valid', '[{"key": "elementId", "value": "social001", "validationStatus": "Valid"}]', NOW() - INTERVAL 41 MINUTE),
(1, 'ErrorEvent', '{"errorCode": 429, "message": "Rate limited"}', 'Valid', '[{"key": "errorCode", "value": 429, "validationStatus": "Valid"}]', NOW() - INTERVAL 40 MINUTE),
(1, 'UserLogout', '{"username": "user10", "timestamp": "2025-11-04T10:56:00"}', 'Valid', '[{"key": "username", "value": "user10", "validationStatus": "Valid"}]', NOW() - INTERVAL 39 MINUTE),
(1, 'PageView', '{"pageId": "blog", "duration": 45000}', 'Valid', '[{"key": "pageId", "value": "blog", "validationStatus": "Valid"}]', NOW() - INTERVAL 38 MINUTE),
(1, 'UserLogin', '{"username": "user21", "timestamp": "2025-11-04T10:58:00"}', 'Valid', '[{"key": "username", "value": "user21", "validationStatus": "Valid"}]', NOW() - INTERVAL 37 MINUTE),
(1, 'FormSubmit', '{"formId": "newsletter", "fields": 1}', 'Valid', '[{"key": "formId", "value": "newsletter", "validationStatus": "Valid"}]', NOW() - INTERVAL 36 MINUTE),
(1, 'UserLogin', '{"username": "user22", "timestamp": "2025-11-04T11:00:00"}', 'Invalid', '[{"key": "username", "value": "user22", "validationStatus": "Valid"}, {"key": "timestamp", "value": "2025-11-04T11:00:00", "validationStatus": "Invalid"}]', NOW() - INTERVAL 35 MINUTE),
(1, 'DataSync', '{"syncId": "sync007", "records": 175}', 'Valid', '[{"key": "syncId", "value": "sync007", "validationStatus": "Valid"}]', NOW() - INTERVAL 34 MINUTE),
(1, 'UserLogout', '{"username": "user11", "timestamp": "2025-11-04T11:02:00"}', 'Valid', '[{"key": "username", "value": "user11", "validationStatus": "Valid"}]', NOW() - INTERVAL 33 MINUTE),
(1, 'ClickEvent', '{"elementId": "promo001", "clickCount": 3}', 'Valid', '[{"key": "elementId", "value": "promo001", "validationStatus": "Valid"}]', NOW() - INTERVAL 32 MINUTE),
(1, 'UserLogin', '{"username": "user23", "timestamp": "2025-11-04T11:04:00"}', 'Valid', '[{"key": "username", "value": "user23", "validationStatus": "Valid"}]', NOW() - INTERVAL 31 MINUTE),
(1, 'ProfileUpdate', '{"userId": 5, "field": "language"}', 'Valid', '[{"key": "userId", "value": 5, "validationStatus": "Valid"}]', NOW() - INTERVAL 30 MINUTE),
(1, 'PageView', '{"pageId": "tutorial", "duration": 90000}', 'Valid', '[{"key": "pageId", "value": "tutorial", "validationStatus": "Valid"}]', NOW() - INTERVAL 29 MINUTE),
(1, 'UserLogin', '{"username": "user24", "timestamp": "2025-11-04T11:06:00"}', 'Valid', '[{"key": "username", "value": "user24", "validationStatus": "Valid"}]', NOW() - INTERVAL 28 MINUTE),
(1, 'ErrorEvent', '{"errorCode": 502, "message": "Bad gateway"}', 'Invalid', '[{"key": "errorCode", "value": 502, "validationStatus": "Valid"}, {"key": "message", "value": "Bad gateway", "validationStatus": "Invalid"}]', NOW() - INTERVAL 27 MINUTE),
(1, 'UserLogout', '{"username": "user12", "timestamp": "2025-11-04T11:08:00"}', 'Valid', '[{"key": "username", "value": "user12", "validationStatus": "Valid"}]', NOW() - INTERVAL 26 MINUTE),
(1, 'FormSubmit', '{"formId": "survey", "fields": 6}', 'Valid', '[{"key": "formId", "value": "survey", "validationStatus": "Valid"}]', NOW() - INTERVAL 25 MINUTE),
(1, 'UserLogin', '{"username": "user25", "timestamp": "2025-11-04T11:10:00"}', 'Valid', '[{"key": "username", "value": "user25", "validationStatus": "Valid"}]', NOW() - INTERVAL 24 MINUTE),
(1, 'DataSync', '{"syncId": "sync008", "records": 225}', 'Valid', '[{"key": "syncId", "value": "sync008", "validationStatus": "Valid"}]', NOW() - INTERVAL 23 MINUTE),
(1, 'ClickEvent', '{"elementId": "ad001", "clickCount": 1}', 'Valid', '[{"key": "elementId", "value": "ad001", "validationStatus": "Valid"}]', NOW() - INTERVAL 22 MINUTE),
(1, 'UserLogout', '{"username": "user13", "timestamp": "2025-11-04T11:12:00"}', 'Valid', '[{"key": "username", "value": "user13", "validationStatus": "Valid"}]', NOW() - INTERVAL 21 MINUTE),
(1, 'PageView', '{"pageId": "gallery", "duration": 25000}', 'Valid', '[{"key": "pageId", "value": "gallery", "validationStatus": "Valid"}]', NOW() - INTERVAL 20 MINUTE),
(1, 'UserLogin', '{"username": "user26", "timestamp": "2025-11-04T11:14:00"}', 'Valid', '[{"key": "username", "value": "user26", "validationStatus": "Valid"}]', NOW() - INTERVAL 19 MINUTE),
(1, 'ProfileUpdate', '{"userId": 6, "field": "theme"}', 'Valid', '[{"key": "userId", "value": 6, "validationStatus": "Valid"}]', NOW() - INTERVAL 18 MINUTE),
(1, 'UserLogout', '{"username": "user14", "timestamp": "2025-11-04T11:16:00"}', 'Valid', '[{"key": "username", "value": "user14", "validationStatus": "Valid"}]', NOW() - INTERVAL 17 MINUTE),
(1, 'UserLogin', '{"username": "user27", "timestamp": "2025-11-04T11:18:00"}', 'Valid', '[{"key": "username", "value": "user27", "validationStatus": "Valid"}]', NOW() - INTERVAL 16 MINUTE),
(1, 'DataSync', '{"syncId": "sync009", "records": 300}', 'Valid', '[{"key": "syncId", "value": "sync009", "validationStatus": "Valid"}]', NOW() - INTERVAL 15 MINUTE),
(1, 'ClickEvent', '{"elementId": "widget001", "clickCount": 4}', 'Valid', '[{"key": "elementId", "value": "widget001", "validationStatus": "Valid"}]', NOW() - INTERVAL 14 MINUTE),
(1, 'FormSubmit', '{"formId": "support", "fields": 5}', 'Valid', '[{"key": "formId", "value": "support", "validationStatus": "Valid"}]', NOW() - INTERVAL 13 MINUTE),
(1, 'PageView', '{"pageId": "pricing", "duration": 12000}', 'Valid', '[{"key": "pageId", "value": "pricing", "validationStatus": "Valid"}]', NOW() - INTERVAL 12 MINUTE),
(1, 'UserLogin', '{"username": "user28", "timestamp": "2025-11-04T11:20:00"}', 'Valid', '[{"key": "username", "value": "user28", "validationStatus": "Valid"}]', NOW() - INTERVAL 11 MINUTE),
(1, 'UserLogout', '{"username": "user15", "timestamp": "2025-11-04T11:22:00"}', 'Valid', '[{"key": "username", "value": "user15", "validationStatus": "Valid"}]', NOW() - INTERVAL 10 MINUTE),
(1, 'ErrorEvent', '{"errorCode": 503, "message": "Service unavailable"}', 'Valid', '[{"key": "errorCode", "value": 503, "validationStatus": "Valid"}]', NOW() - INTERVAL 9 MINUTE),
(1, 'UserLogin', '{"username": "user29", "timestamp": "2025-11-04T11:24:00"}', 'Valid', '[{"key": "username", "value": "user29", "validationStatus": "Valid"}]', NOW() - INTERVAL 8 MINUTE),
(1, 'ProfileUpdate', '{"userId": 7, "field": "notifications"}', 'Valid', '[{"key": "userId", "value": 7, "validationStatus": "Valid"}]', NOW() - INTERVAL 7 MINUTE),
(1, 'DataSync', '{"syncId": "sync010", "records": 250}', 'Valid', '[{"key": "syncId", "value": "sync010", "validationStatus": "Valid"}]', NOW() - INTERVAL 6 MINUTE),
(1, 'UserLogout', '{"username": "user16", "timestamp": "2025-11-04T11:26:00"}', 'Valid', '[{"key": "username", "value": "user16", "validationStatus": "Valid"}]', NOW() - INTERVAL 5 MINUTE),
(1, 'PageView', '{"pageId": "contact", "duration": 6000}', 'Valid', '[{"key": "pageId", "value": "contact", "validationStatus": "Valid"}]', NOW() - INTERVAL 4 MINUTE),
(1, 'ClickEvent', '{"elementId": "footer001", "clickCount": 1}', 'Valid', '[{"key": "elementId", "value": "footer001", "validationStatus": "Valid"}]', NOW() - INTERVAL 3 MINUTE),
(1, 'FormSubmit', '{"formId": "quote", "fields": 10}', 'Valid', '[{"key": "formId", "value": "quote", "validationStatus": "Valid"}]', NOW() - INTERVAL 2 MINUTE),
(1, 'UserLogin', '{"username": "user30", "timestamp": "2025-11-04T11:28:00"}', 'Valid', '[{"key": "username", "value": "user30", "validationStatus": "Valid"}]', NOW() - INTERVAL 1 MINUTE);
